### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tookunn1213** [tookunn1213/go-termtable#1]
- [ ] expand column width and row height
- [x] sort record
- [x] filter record
- [ ] refactoring sometimes
- [ ] column offset
- [ ] swiching type of border line
- [ ] add comment in code
